### ISSUE TITLE
Questionable SSH_MSG_UNIMPLEMENTED handling

### ISSUE THREAD

**Issue by DCNick3** [Aimeast/FxSsh#19]
The SSH_MSG_UNIMPLEMENTED handler currently sends unimplemented message back:

https://github.com/Aimeast/FxSsh/blob/dbacd36d14698d0f85a28c44301e99e172e64113/FxSsh/Session.cs#L600-L602

It's weird behavior. `openssh`, for example, just logs this message without doing anything with it:

https://github.com/openssh/openssh-portable/blob/62dd70613b77b229f53db3cc1c3e8a206fa2b582/packet.c#L1725

**Comment by Aimeast** [comment]
Hi, what's type message openssh send? what message fxssh received? what channel was opened?

how reproduce this issue?

**Comment by DCNick3** [comment]
It's not compatibility issue, I have just read code and found this behaviour weird: when server receives SSH_MSG_UNIMPLEMENTED message it sends back the same message without even changing it. This is clearly not tge case where it should be sent. 

openssh was referred as example of another implementation behaviour: it ignores it.

**Comment by Aimeast** [comment]
I am understanded. Can you send a PR fix this? Tks.

**Comment by Aimeast** [comment]
I have read the code again, it is not weird, it is designed. Because if any side (client or server) received an unknown package, a `SSH_MSG_UNIMPLEMENTED` MUST return. see [RFC4253 11.4](https://tools.ietf.org/html/rfc4253#section-11.4)

The codes at the Session.cs

https://github.com/Aimeast/FxSsh/blob/dev/FxSsh/Session.cs#L342-L350

Create an `UnimplementedMessage` if the package is unknown. So, we need to detect the `UnimplementedMessage` which is unknown package or received a `SSH_MSG_UNIMPLEMENTED` from client. So, the right things we need to do:

1. Add a overload `OnLoad` for `UnimplementedMessage.cs`, pass the `SequenceNumber`
2. Add a condition for `HandleMessage` https://github.com/Aimeast/FxSsh/blob/dev/FxSsh/Session.cs#L600-L603, which is `if (message.UnimplementedMessageType != 0) SendMessage(message)`

Please update the PR.

**Comment by DCNick3** [comment]
Hmm, I got your point. But I find the current handling scheme very misleading: it uses `HandleMessage` for the packet that is to be sent, but all other overloads take care of processing the received packet. Shouldn't `ReceiveMessage` (that takes care of decoding message and creating message object) take care of it?

**Comment by Aimeast** [comment]
It is maybe cause misleading. The `HandleMessage` is for handle and process message. But `UnimplementedMessage` is a specific message. No matter where, we always have a place to deal with it. I design it at `HandleMessage`. Maybe we can add some comment on method `HandleMessage(UnimplementedMessage message)` help everybody to understand it.

We are not necessary to create a repetitive new message object, because it is the same.

**Comment by DCNick3** [comment]
Another solution may be splitting cases (creating different classes for it?) where we received message that is not implemented and remote sent `SSH_MSG_UNIMPLEMENTED`

**Comment by Aimeast** [comment]
Good idea, do you have specific advice?

**Comment by DCNick3** [comment]
Not yet, will try to come up with something.

**Comment by DCNick3** [comment]
Well, I think a good approach for handling this would be making current `UnimplementedMessage` an exception. This would split the message class and the fact of receiving unimplemented message. `EstablishConnection` would be a good place to catch it and send an `UnimplementedMessage` to remote. This way `HandleMessage(UnimplementedMessage)` could be used only as a message handler, not as handler for exceptional situations.

**Comment by Aimeast** [comment]
throw-catch an exception will break the message loop, we need redesign message loop if we consider this mechanism. may more complexity.

**Comment by DCNick3** [comment]
By message loop you mean [this](https://github.com/Aimeast/FxSsh/blob/dev/FxSsh/Session.cs#L131-L135)? try-catch clause for `UnimplementedMessageException` could be added inside this loop, so after handling it message loop will continue to retrieve and process messages.

**Comment by Aimeast** [comment]
Or, a way is to create a new type of message such as `UnknowMessage : Message` (or more exact class name) and replace https://github.com/Aimeast/FxSsh/blob/dev/FxSsh/Session.cs#L346 `UnimplementedMessage` as `UnknowMessage`. Then, process it in the message loop https://github.com/Aimeast/FxSsh/blob/dev/FxSsh/Session.cs#L131-L135

```
if (message is UnknowMessage)
    ReceivedUnknowMessage(message);
else
    HandleMessageCore(message);
```

**Comment by DCNick3** [comment]
Or even process it with its own `MessageHandler` (with adding comment, saying it's not an actual received message).

**Comment by Aimeast** [comment]
As you opinion above, it is difference definitions between received a unknown message and a real unimplemented message. Split it will make a better responsibility. Looks like the best solution is yesterday I answered, split it on message loop via `UnimplementedMessage` and `UnknowMessage`. Please update the PR if there's have no better solution.

**Comment by Aimeast** [comment]
Hi @DCNick3, do you have progress in this?

**Comment by DCNick3** [comment]
I updated the #21.
